<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0-windows7.0</TargetFramework>
    <Configuration Condition=" '$(Configuration)' == '' ">Release</Configuration>
    <OutputType>Library</OutputType>
	<PublishTrimmed>True</PublishTrimmed>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <GenerateAssemblyInfo>True</GenerateAssemblyInfo>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
    <Configurations>Debug;Release</Configurations>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <DebugType>pdbonly</DebugType>
    <Nullable>enable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ImplicitUsings>disable</ImplicitUsings>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <ProduceReferenceAssembly>False</ProduceReferenceAssembly>
    <PublishAot>True</PublishAot>
    <AnalysisLevel>latest</AnalysisLevel>
    <Platforms>AnyCPU;x64;x86;ARM64</Platforms>
    <PackageReadmeFile>..\README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/massgravel/TSforge.git</RepositoryUrl>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <PlatformTarget>AnyCPU</PlatformTarget>
    <Optimize>True</Optimize>
    <FileAlignment>4096</FileAlignment>
    <IsAotCompatible>True</IsAotCompatible>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <PlatformTarget>x64</PlatformTarget>
    <Optimize>True</Optimize>
    <FileAlignment>4096</FileAlignment>
    <IsAotCompatible>True</IsAotCompatible>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|ARM64'">
    <PlatformTarget>ARM64</PlatformTarget>
    <Optimize>True</Optimize>
    <FileAlignment>4096</FileAlignment>
    <IsAotCompatible>True</IsAotCompatible>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x86'">
    <PlatformTarget>x86</PlatformTarget>
    <Optimize>True</Optimize>
    <FileAlignment>4096</FileAlignment>
    <IsAotCompatible>True</IsAotCompatible>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <PlatformTarget>AnyCPU</PlatformTarget>
    <FileAlignment>4096</FileAlignment>
    <IsAotCompatible>True</IsAotCompatible>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <PlatformTarget>x64</PlatformTarget>
    <FileAlignment>4096</FileAlignment>
    <IsAotCompatible>True</IsAotCompatible>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|ARM64'">
    <PlatformTarget>ARM64</PlatformTarget>
    <FileAlignment>4096</FileAlignment>
    <IsAotCompatible>True</IsAotCompatible>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x86'">
    <PlatformTarget>x86</PlatformTarget>
    <FileAlignment>4096</FileAlignment>
    <IsAotCompatible>True</IsAotCompatible>
  </PropertyGroup>
  <ItemGroup>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.ServiceProcess.ServiceController" Version="9.0.3" />
  </ItemGroup>
</Project>